USE [master]
GO
CREATE LOGIN [Josh] WITH PASSWORD=N'Pass@word', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
/****** Object:  Database [SampleData]    Script Date: 3/30/2021 11:55:07 PM ******/
CREATE DATABASE [SampleData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SampleData', FILENAME = N'/var/opt/mssql/data/SampleData.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SampleData_log', FILENAME = N'/var/opt/mssql/data/SampleData_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [SampleData] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SampleData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [SampleData] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [SampleData] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [SampleData] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [SampleData] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [SampleData] SET ARITHABORT OFF 
GO
ALTER DATABASE [SampleData] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [SampleData] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [SampleData] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [SampleData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [SampleData] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [SampleData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [SampleData] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [SampleData] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [SampleData] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [SampleData] SET  DISABLE_BROKER 
GO
ALTER DATABASE [SampleData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [SampleData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [SampleData] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [SampleData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [SampleData] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [SampleData] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [SampleData] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [SampleData] SET RECOVERY FULL 
GO
ALTER DATABASE [SampleData] SET  MULTI_USER 
GO
ALTER DATABASE [SampleData] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [SampleData] SET DB_CHAINING OFF 
GO
ALTER DATABASE [SampleData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [SampleData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [SampleData] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'SampleData', N'ON'
GO
ALTER DATABASE [SampleData] SET QUERY_STORE = OFF
GO
USE [SampleData]
GO
/****** Object:  User [Josh]    Script Date: 3/30/2021 11:55:07 PM ******/
CREATE USER [Josh] FOR LOGIN [Josh] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  DatabaseRole [SampleData]    Script Date: 3/30/2021 11:55:07 PM ******/
CREATE ROLE [SampleData]
GO
ALTER ROLE [db_owner] ADD MEMBER [Josh]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 3/30/2021 11:55:07 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [SampleData]
GO
ALTER DATABASE [SampleData] SET  READ_WRITE 
GO

INSERT INTO [dbo].[Product]
           ([Name])
     VALUES
           ('Book')
GO

INSERT INTO [dbo].[Product]
           ([Name])
     VALUES
           ('Tape')
GO

INSERT INTO [dbo].[Product]
           ([Name])
     VALUES
           ('CD')
GO
